spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/revie
    username: revie
    password: revie1234
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  data:
    mongodb:
      uri: mongodb://root:root1234@localhost:27017/revie?authSource=admin
      database: revie

# application.yml
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG