spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/revie
    username: revie
    password: revie1234
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  data:
    mongodb:
      uri: mongodb://revie:revie1234@localhost:27017/revie?authSource=revie
      database: revie

  webflux:
    base-path: /api

logging:
  level:
    root: INFO
    com.revie: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.mongodb: DEBUG
    io.r2dbc.pool: DEBUG