spring:
  application:
    name: revie-backend

server:
  port: 8080

# GitHub API 설정
github:
  token: ${GITHUB_TOKEN:your-github-token}
  api-url: https://api.github.com

# Gemini API 설정
gemini:
  api-key: ${GEMINI_API_KEY:your-gemini-api-key}
  model: gemini-2.0-flash-exp
  embedding-model: text-embedding-004
  max-output-tokens: 8192
  temperature: 0.7